version: '3.8'

services:
  # MySQL Database
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/library/mysql:8.0
    container_name: ipam_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: ipam
      MYSQL_USER: ipam_user
      MYSQL_PASSWORD: ipam_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ipam_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/library/redis:6-alpine
    container_name: ipam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ipam_network
    restart: unless-stopped

  # Backend API Service
  backend:
    build: ./backend
    container_name: ipam_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://ipam_user:ipam_pass123@mysql:3306/ipam
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - mysql
      - redis
    networks:
      - ipam_network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Frontend Web Application
  frontend:
    build: ./frontend
    container_name: ipam_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ipam_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  ipam_network:
    driver: bridge